config/routes.rb
Projekt::Application.routes.draw do
  resources :category_bundles


  resources :categories


  resources :roles


  resources :microposts


  #resources :sessions,   :only => [:new, :create, :destroy]
  #resources :microposts, :only => [:create, :destroy]
  
  get "microposts/show"
  
  get "users/show"
  get "users/index"

  devise_for :users
  #devise_for :users do
	#get 'sign_out',    :to => 'devise/sessions#destroy'
  #end
  resources :users

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  get "pages/help"

  
  match '/home',    :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  #match '/users/sign_out',    :to => 'devise/sessions#destroy'
  
  
  root :to => 'pages#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :avatar, :role
  has_attached_file :avatar,
					:styles => {
					  :mini => "40x40>",
                      :thumb => "75x75>",
                      :small => "150x150>"
                    }  
					
	def self.search(search, page)
		paginate :per_page => 5, :page => page,
            :conditions => ['name like ?', "%#{search}%"],
            :order => 'name'
	end
	
	has_one :roles
	has_many :microposts, :dependent => :destroy
	
	has_many :category_bundles
    has_many :categories, through: :category_bundles
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
  before_filter :authenticate_user!
	
  # GET /users
  # GET /users.json
  def index
    #@users = User.all
	@users = User.paginate(:per_page => 3, :page => params[:page])
	@users = User.search(params[:search], params[:page])
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #@user = User.find(params[:id])
   # respond_to do |format|
     # format.html # show.html.erb
     # format.json { render json: @user }
    #end
	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @titre = @user.name
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
		# Tell the UserMailer to send a welcome Email after save
        UserMailer.welcome_email(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def is_current_user(user)
    return user.id == current_user.id
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <p>
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>



<table>
  <tr>
    <th>Avatar</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= image_tag user.avatar.url(:thumb) %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @users %>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<table class="profile">
  <tr>
    <td class="main">
		<%= image_tag @user.avatar.url(:small) %><br />
		
		<% unless @user.microposts.empty? %>
        <table class="microposts" summary="Micro-messages de l'utilisateur">
			<%= render @microposts %>
        </table>
        <%= will_paginate @microposts %>
      <% end %>
    </td>
	
    <td class="sidebar round">
		<strong>Role: </strong> <%= @user.role %><br />
		<strong>Name: </strong> <%= @user.name %><br />
		<strong>URL: </strong> <%= link_to user_path(@user), @user %><br />
		<strong>Messages: </strong> <%= @user.microposts.count %><br /><br />
		
		<% if is_current_user(@user) %>
			<%= link_to 'New Micropost', new_micropost_path %><br /><br />
			<%= link_to 'Edit Profile', edit_user_path(@user) %>
		<% end %>

    </td>
  </tr>
</table>