config/routes.rb
Projekt::Application.routes.draw do
  resources :category_bundles


  resources :categories


  resources :roles


  resources :microposts


  #resources :sessions,   :only => [:new, :create, :destroy]
  #resources :microposts, :only => [:create, :destroy]
  
  get "microposts/show"
  
  get "users/show"
  get "users/index"

  devise_for :users
  #devise_for :users do
	#get 'sign_out',    :to => 'devise/sessions#destroy'
  #end
  resources :users

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  get "pages/help"

  
  match '/home',    :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  #match '/users/sign_out',    :to => 'devise/sessions#destroy'
  
  
  root :to => 'pages#home'
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<p>
		<nav class="round">
			<ul>
				<li><%= link_to "Home", root_path  %></li>
				<li><%= link_to "Help", help_path  %></li>
				<% if user_signed_in? %>
				  <li><%= link_to "Users", users_path  %></li>
				  <li><%= link_to "Profile", current_user  %></li>
				  <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
				<% else %>
					<li><%= link_to "Sign in", new_user_session_path %>/<%= link_to "Sign up", new_user_registration_path %></li>
				<% end %>
			</ul>
		</nav>
		<%= image_tag("logo.png", :alt => "Application exemple", :class => "round") %>
		<%= form_tag("/search_user", :method => "get") do %>
		<%= label_tag(:q, "Search for User:") %>
		<%= text_field_tag(:q) %>
		<%= submit_tag("Go") %>
		<% end %>
	</p>
	<p>
		<% if user_signed_in? %>
			<%= image_tag current_user.avatar.url(:mini) %>
			<b>Welcome <%= current_user.name%></b>
		<% end %>
		
		
	</p>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
        <%= render 'layouts/header' %>
        <section class="round">
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>